### ISSUE TITLE
Initial command execution and changing of effective user id

### ISSUE THREAD

**Issue by rnijveld** [memorysafety/sudo-rs#1]
* Have a binary with setuid flag set (https://linux.die.net/man/2/setuid)
* Be able to run an arbitrary command as provided via command line arguments
* Set the effective user id to something else than root

**Comment by marlonbaeten** [comment]
A naive implementation is finished in in https://github.com/memorysafety/sudo-rs/blob/259121fd1b02ac18be00ddc3653fc5d908f26b98/lib/sudo-common/src/exec.rs
The follow-up issue is #56
