### ISSUE TITLE
sudoers parser fails when sudoers file does not contain a trailing newline

### ISSUE THREAD

**Issue by japaric** [memorysafety/sudo-rs#102]
Steps to reproduce: (note the `-n` flag passed to `echo`)
``` console
# echo -n 'root    ALL=(ALL:ALL) NOPASSWD: ALL' > /etc/sudoers
# sudo true
Parse error: missing line terminator at end of file
```

the original sudo accepts this sudoers file.

adding a new line to the end of the file works

``` console
# echo 'root    ALL=(ALL:ALL) NOPASSWD: ALL' > /etc/sudoers
# sudo true
# echo $?
0
```

**Comment by japaric** [comment]
reminder: when this get fixed please remove this HACK I added to keep existing tests passing

https://github.com/memorysafety/sudo-rs/blob/15b34e89efdf81f54a4a6fb979eadd88b1c1548d/test-framework/sudo-test/src/lib.rs#L65-L66

**Comment by squell** [comment]
Note (repeating private communication for public consumption): this is just a diagnostic, e.g. running on a3038ae038e9f27400752facce975da2e19a3c73 with a sudoers file generated by:
```
# echo -n "ALL ALL=NOPASSWD: ALL" > /etc/sudoers.test
```
You get:
```
$ whoami
<your user>
$ ./sudo whoami
/etc/sudoers.test:1:22: missing line terminator at end of file
ALL ALL=NOPASSWD: ALL
                     ^
root
```
I.e., functionality is maintained; you just get warned about something that on production machines should not happen (and is prevented by proper visudo use right now, I believe).

Not having line-endings at the end of sudoers file can be hazardous if they are updated by scripts that expect them to be there (e..g. https://stackoverflow.com/questions/41298208/how-to-append-a-line-at-the-end-of-etc-sudoers-file-using-shell-script-without)
