### ISSUE TITLE
wrong exit code when child process is terminated by a signal

### ISSUE THREAD

**Issue by japaric** [memorysafety/sudo-rs#112]
relevant test (added in  #111)

https://github.com/memorysafety/sudo-rs/blob/a536a64d75df5dd90f4d90d8a18a59bcf9d1e2f8/test-framework/sudo-compliance-tests/src/child_process/signal_handling/mod.rs#L57-L66

the original sudo exits with code 143 -- the same code `sh -c 'kill $$'` exits with. sudo-rs exits with code 1 in this case

cc @pvdrz

**Comment by pvdrz** [comment]
hmmm interesting. I wonder if this could be just us not reporting the exit code of the command we're running or something. I'll try to add some logging and check what happens locally.

**Comment by pvdrz** [comment]
Ok after taking a deeper look what happens is that the command exits with `SIGTERM` but `std::process::ExitStatus` does not have an exit code for it so we just `exit(1)`

That being said there are some nasty bugs happening with signal handling. I'll open more issues about it next week
