### ISSUE TITLE
`sudo -g #1234` is rejected if the requested group ID is unassigned / does not exist

### ISSUE THREAD

**Issue by japaric** [memorysafety/sudo-rs#137]
relevant test

https://github.com/memorysafety/sudo-rs/blob/bb0fed6a2d8cf3ca3bf771a868d21d0e1d16c77b/test-framework/sudo-compliance-tests/src/flag_group.rs#L81-L100

sudo-rs: `sudo -g #1234 id -g` fails with `Error: GroupNotFound("#1234")`

original sudo: returns `1234`

**Comment by pvdrz** [comment]
Apparently sudo decided to change this behavior recently see https://www.sudo.ws/docs/upgrade/ for version 1.8.30:
> Starting with version 1.8.30, sudo will no longer allow commands to be run as a user or group ID that is not in the password or group databases by default. Previously, sudo would always allow unknown user or group IDs if the sudoers entry permitted it, including via the ALL alias. The old behavior can be restored by setting the new "allow_unknown_runas_id” Defaults setting in the sudoers file.

Just for reference. On my local machine I have sudo version 1.9.13p3 and it behaves like this:
```shell
$ sudo -g#1234 id -g
sudo: unknown group #1234
```

I guess we still could fix this if we want to support this `allow_unknown_runas_id` option.

**Comment by squell** [comment]
Note: for any things where sudo recently changed behaviour, we should feel more free to also make up our own mind (e.g. original sudo isn't always a drop-in replacement for original sudo). I.e. I would heed the direction that original sudo is taking but not feel compelled to add in a lot of legacy backward support for this "feature" which sounds a bit dubious anyway. (Unless we notice `allow_unknown_runasid` is a widely used setting.)
