### ISSUE TITLE
sudoers: `:some_group` Runas_Spec rejects `sudo -g some-group` as regular user

### ISSUE THREAD

**Issue by japaric** [memorysafety/sudo-rs#141]
relevant test

https://github.com/memorysafety/sudo-rs/blob/8d44fc9cab60b55c4dc7e5bad2fb36e45a9421e5/test-framework/sudo-compliance-tests/src/sudoers/run_as.rs#L172-L187

setup
``` console
$ useradd --no-user-group --no-create-home ferris
$ groupadd rustaceans
```

sudo-rs: `sudo -g rustaceans true` as user `ferris` fails with `Error: Authentication("no permission")`. running the same command as root works.

original sudo: both cases work

**Comment by squell** [comment]
This is partly related to #134  (empty run_as userlist), but curiously `sudo -u ferris -g rustaceans true` also seems to fail.
