### ISSUE TITLE
Users should never be granted sudo privileges to execute files that are writable by the user

### ISSUE THREAD

**Issue by marlonbaeten** [memorysafety/sudo-rs#157]
Users should [never](https://www.sudo.ws/docs/man/1.9.13/sudo.man/#never) be granted sudo privileges to execute files that are writable by the user or that reside in a directory that is writable by the user. If the user can modify or replace the command there is no way to limit what additional commands they can run.

**Comment by squell** [comment]
Running original`sudo` as root will allow you to execute `/bin/ls`. So it is clearly not **never**-never. This sound like it needs another deep dive into the sudo source code.

**Comment by squell** [comment]
As @japaric mentioned in private communication, this is advice for users of sudo. In general this would be pretty hard to write a check for  (especially one that could run at `visudo` time). So I'm closing this.
