### ISSUE TITLE
Add use_pty support

### ISSUE THREAD

**Issue by squell** [memorysafety/sudo-rs#159]
Do something with the `use_pty` flag (this runs the spawned process in a seperate pty)

**Comment by hannob** [comment]
`use_pty` should not just be implemented, but also be enabled by default, otherwise on Linux there are privilege escalations with TIOCSTI and TIOCLINUX ioctls. See also https://github.com/sudo-project/sudo/issues/258

**Comment by hartwork** [comment]
@pvdrz you mean allowing explicit execution without a PTY versus not supporting that at all?
I think it could allow bypassing any potential bugs for known trusted code while the PTY support code is still young?
