### ISSUE TITLE
Session handling

### ISSUE THREAD

**Issue by rnijveld** [memorysafety/sudo-rs#191]
Right now we have no way to run code after running a command, and no way to keep state between the pre-run and post-run parts of the code, but we need this infrastructure especially for PAM sessions.

**Comment by pvdrz** [comment]
@rnijveld do you mean something like a closure to pass before and after executing a command? what kind of info should be available in pre-run and post-run?

**Comment by rnijveld** [comment]
I think this was solved in #248
