### ISSUE TITLE
User-facing documentation

### ISSUE THREAD

**Issue by squell** [memorysafety/sudo-rs#206]
- [x] man pages
- [x] README which contains command flags, etc
- [x] security policy documentation
- [x] deviations/limitations compared to original sudo

**Comment by sdroege** [comment]
It would also be nice to compare to existing Rust implementations and what makes this one different. There's for example https://gitlab.com/edneville/please , which has a different configuration file format and is not a 100% drop-in replacement.

**Comment by squell** [comment]
> It would also be nice to compare to existing Rust implementations and what makes this one different. There's for example https://gitlab.com/edneville/please , which has a different configuration file format and is not a 100% drop-in replacement.

We could also draw a comparison to `doas` (since many people often compare `sudo-rs` to that): e.g. the sudo-rs team does like that configuration format too but there are also some things (like PTY support) that `doas` doesn't have.

I think something like that would be better suited to a more general FAQ though; which I'll make an issue for.

**Comment by squell** [comment]
CC 782
