### ISSUE TITLE
Test randomly fails

### ISSUE THREAD

**Issue by pvdrz** [memorysafety/sudo-rs#216]
I'm just opening this issue to keep track of it in case it happens again. CI was running for #212 and a test that shouldn't be affected by the changes of this PR failed: https://github.com/memorysafety/sudo-rs/actions/runs/4612410116/jobs/8153273441/ Then, I reran the failed job and all the tests passed https://github.com/memorysafety/sudo-rs/actions/runs/4612410116/jobs/8154338520

The test that failed is `signal_sent_by_child_process_is_ignored`.

**Comment by pvdrz** [comment]
After checking the test it might be that this happens just due to the nature of how it works as it needs to sleep to give enough time to a signal delivery.

cc @japaric

**Comment by squell** [comment]
Is this still an issue? I haven't seen it happen in a while.

**Comment by japaric** [comment]
I made some tests less brittle in #327 but didn't touch this one. I haven't seen this one fail in a long time either.

**Comment by squell** [comment]
Closing this as we have other CI problems and this one doesn't seem to be happening (re-open if it returns).
