### ISSUE TITLE
Execution should only continue after a failed chdir if a login shell was requested

### ISSUE THREAD

**Issue by rnijveld** [memorysafety/sudo-rs#241]
In original sudo:
* When we run a login shell (and thus want to chdir to the user homedir) we will eventually have to login as the user somehow, so even if chdir fails we continue running the shell for the target user. This is also what `su` does for `su - user` if the user homedir does not exist.
* In all other cases, a failed chdir results in the command not executing:
   ```shell
   sudo --chdir=/path/to/nowhere ls
   sudo: unable to change directory to /path/to/nowhere: No such file or directory
   sudo: unable to execute /usr/bin/ls: No such file or directory
   ```
   In such cases, continuing after a failed chdir could mean that a completely different command executes, so it makes sense to not execute anything in such cases.

**Comment by pvdrz** [comment]
Oh this is a very interesting catch :P We are handling `--chdir` and `-i` as basically the same but this shouldn't be hard to fix. I call dibs
