### ISSUE TITLE
Go through sudo CVEs and take actions based on relevancy

### ISSUE THREAD

**Issue by rnijveld** [memorysafety/sudo-rs#261]
Sudo has about 140 CVEs associated with it, and some of them might be relevant for our implementation as well. We should go through each of them and add a table to our repository indicating for each CVE whether or not it is relevant (and the reason for that) and if the CVE may be relevant there should be some sort of test in our test framework that makes sure that we are not vulnerable.

**Comment by squell** [comment]
Made pass through the sudo advisories and inventoried them in #96 to be made into compliance tests. There is [one advisory](https://www.sudo.ws/security/advisories/tty_tickets/) that we need to look into further before we can close this one.

**Comment by squell** [comment]
We also read `/proc` to get the name of the TTY for timestamping purposes, so sudo-rs also does not allow bypassing the ticket constraints (which right now are fixed in sudo-rs, anyway).
