### ISSUE TITLE
Command hashing

### ISSUE THREAD

**Issue by pvdrz** [memorysafety/sudo-rs#267]
Should we actually support filtering commands by the hash? What are the use cases?

**Comment by squell** [comment]
I am drafting a PR that *removes* digest support from sudo-rs, we can then see if we like that or not. It does mean we explicitly are not compatible with original sudo on that front (but we decided on that during sudo-rs WG1)

**Comment by squell** [comment]
Closed by #302 (not sure why this is not happening automatically).
