### ISSUE TITLE
Dereference of a possible returned NULL in pam_getenvlist

### ISSUE THREAD

**Issue by kpp** [memorysafety/sudo-rs#270]
https://github.com/memorysafety/sudo-rs/blob/fe8bf15a238cc48c4518fe9d5ec593fdef89d863/lib/sudo-pam/src/lib.rs#L433

According to https://linux.die.net/man/3/pam_getenvlist:

```
Return Values

The pam_getenvlist function returns NULL on failure.
```

**Comment by rnijveld** [comment]
Good catch! Thanks for having a look!
