### ISSUE TITLE
PamContext.pamh should not be an Option

### ISSUE THREAD

**Issue by kpp** [memorysafety/sudo-rs#271]
https://github.com/memorysafety/sudo-rs/blob/fe8bf15a238cc48c4518fe9d5ec593fdef89d863/lib/sudo-pam/src/lib.rs#L21

There is no need to because there is no way to construct PamContext with a pamh=None. Also it will help to clean up mess with `context.pamh = Some(unsafe { &mut *pamh });` and `match &mut self.pamh {`.

**Comment by rnijveld** [comment]
This was a remnant of a previous implementation of PamContext, I've cleaned up the code!
