### ISSUE TITLE
No action if password exceeds PAM_MAX_RESP_SIZE

### ISSUE THREAD

**Issue by kpp** [memorysafety/sudo-rs#289]
https://github.com/memorysafety/sudo-rs/blob/55e09d74d43a1bb185893cb4a3f9e483e0a2d052/lib/sudo-pam/src/rpassword.rs#L81

That's an unlikely situation but there is no actions taken if the password is longer than PAM_MAX_RESP_SIZE (512) bytes.

**Comment by squell** [comment]
Thanks for the spot check; the impact of this is slight, if someone has a password of PAM_MAX_RESP_SIZE this doesn't really make an attackers job easier, but there should be some defensive coding to check that the input iterator has been exhausted.
