### ISSUE TITLE
implement the `--validate` flag

### ISSUE THREAD

**Issue by japaric** [memorysafety/sudo-rs#395]
relevant tests

https://github.com/memorysafety/sudo-rs/blob/affd48c085c3fb3cc58d1a9fcd550854f2ddf4c7/test-framework/sudo-compliance-tests/src/timestamp.rs#L116

https://github.com/memorysafety/sudo-rs/blob/affd48c085c3fb3cc58d1a9fcd550854f2ddf4c7/test-framework/sudo-compliance-tests/src/timestamp.rs#L139

**Comment by squell** [comment]
Note for the implementer of this issue: this issue should be interpreted as a limited implementation, i.e. "implement --validate, always asking for a password"; the more extensive "don't ask for a password if NOPASSWD is specified" is a separate issue.
