### ISSUE TITLE
should accept `--chdir` values that match the current working directory regardless of the CWD tag

### ISSUE THREAD

**Issue by japaric** [memorysafety/sudo-rs#401]
relevant tests

https://github.com/memorysafety/sudo-rs/blob/e0b03750cd1de37c47c0ce10538f535244491f75/test-framework/sudo-compliance-tests/src/flag_chdir.rs#L133

https://github.com/memorysafety/sudo-rs/blob/e0b03750cd1de37c47c0ce10538f535244491f75/test-framework/sudo-compliance-tests/src/flag_chdir.rs#L150

when the CWD tag is set this can result in surprising behavior

**Comment by squell** [comment]
New versions of ogsudo (e.g. the one currently in trixie) have the same behaviour as sudo-rs! 🎉
