### ISSUE TITLE
sudoers: naming via Cmnd_Alias does not work as expected (underscores)

### ISSUE THREAD

**Issue by BriocheBerlin** [memorysafety/sudo-rs#402]
Naming a `Cmnd_Alias` using an underscore like so `UNDER_SCORE` works.

relevant test:
https://github.com/memorysafety/sudo-rs/blob/c060a25d8e7f0e07ba7684ce2b125eb49c107e23/test-framework/sudo-compliance-tests/src/sudoers/cmnd_alias.rs#L49-L60

ogsudo: this operation works.
sudo-rs: 
```
expecting `=' but found `_'
Cmnd_Alias UNDER_SCORE = /bin/true, /bin/ls
                ^
/etc/sudoers.test:2:24: garbage at end of line
ALL ALL=(ALL:ALL) UNDER_SCORE
                       ^
sudo-rs: authentication failed: I'm sorry root. I'm afraid I can't do that
```

**Comment by squell** [comment]
Aliases can also contain digits: `NAME ::= [A-Z]([A-Z][0-9]_)*`
