### ISSUE TITLE
`RunAs_Spec`: given `(user:group)` `sudo -g group` should be allowed

### ISSUE THREAD

**Issue by japaric** [memorysafety/sudo-rs#403]
relevant test

https://github.com/memorysafety/sudo-rs/blob/e0b03750cd1de37c47c0ce10538f535244491f75/test-framework/sudo-compliance-tests/src/sudoers/run_as.rs#L268

**Comment by BriocheBerlin** [comment]
The same happens on `Runas_Alias`, relevant tests (both failing on group):
https://github.com/memorysafety/sudo-rs/blob/7811f5627709b2cdbb584ab2debf32dfb717df62/test-framework/sudo-compliance-tests/src/sudoers/runas_alias.rs#L356
https://github.com/memorysafety/sudo-rs/blob/7811f5627709b2cdbb584ab2debf32dfb717df62/test-framework/sudo-compliance-tests/src/sudoers/runas_alias.rs#L294

**Comment by squell** [comment]
So some investigation; a recurring theme is that if you specify `-g` and not `-u`, sudo just ignores the first half of the runas specifier. To support this in the `Request` structure in `sudoers`, we should change the group field to an `Option<>` (and adjust the logic accordingly).

**Comment by squell** [comment]
Or simpler: if we request to be a group that the requested user is not a party to (i.e. can only be the result of `-g`), add the current-user (as an exception) as an allowed user. That way the API stays stable.
