### ISSUE TITLE
sudoers: `ALL ALL = ALL` should allow `sudo -u root -g some-group some-command`

### ISSUE THREAD

**Issue by japaric** [memorysafety/sudo-rs#427]
relevant test

https://github.com/memorysafety/sudo-rs/blob/6d2ca26b540f4ef5d0627c82eed202363fd7683c/test-framework/sudo-compliance-tests/src/sudoers/run_as.rs#L353

Note that the [manual](https://www.sudo.ws/docs/man/1.9.5/sudoers.man/#Runas_Spec) appears to indicate that this operation should not be allowed (emphasis mine):

> If no Runas_Spec is specified the command may be run as root and *no group may be specified*.

**Comment by squell** [comment]
So what groups are allowed? Any? (I'm leaning towards this becoming a #wontfix due to the "Feature should solve a problem" and "Common use case" criteria)

**Comment by squell** [comment]
@japaric My sudoers manpage says: 
> If no Runas_Spec is specified, the command may only be run as root and the group, if specified, must be one that root is a member of.

**Comment by millert** [comment]
I consider this a bug in sudo and will be addressing it in sudo 1.9.14.  I think you should implement the documented behavior as you have done.

**Comment by squell** [comment]
Note: `wontfix` but not closing this issue: the compliance test needs to be changed into a positive regression test for us.

**Comment by millert** [comment]
FYI this has been fixed in sudo by [4710283](https://github.com/sudo-project/sudo/commit/471028351650aa4477e59a1701608ffae5b1d4a2)
