### ISSUE TITLE
`Runas_Alias`: `sudo -u user -g some-group some-command` not allowed, unexpected behaviour

### ISSUE THREAD

**Issue by BriocheBerlin** [memorysafety/sudo-rs#432]
`Runas_Alias` behaves differently compared to `Runas_Spec`.
The [manual](https://www.sudo.ws/docs/man/sudoers.man/#Runas_Spec) states:

> Multiple users and groups may be present in a *Runas_Spec*, in which case the user may select any combination of users and groups via the **-u** and **-g** options. In this example:
`alan	ALL = (root, bin : operator, system) ALL`
> user **alan**  may run any command as either user **root** or **bin**, optionally setting the group to operator or system.

Passing the `-g` and `-u` arguments at the same time works for `Runas_Spec`, relevant test:
https://github.com/memorysafety/sudo-rs/blob/7811f5627709b2cdbb584ab2debf32dfb717df62/test-framework/sudo-compliance-tests/src/sudoers/run_as.rs#L316-L332

But for ogsudo, it doesn't work on `Runas_Alias` , relevant tests:
https://github.com/memorysafety/sudo-rs/blob/7811f5627709b2cdbb584ab2debf32dfb717df62/test-framework/sudo-compliance-tests/src/sudoers/runas_alias.rs#L384-L416

https://github.com/memorysafety/sudo-rs/blob/7811f5627709b2cdbb584ab2debf32dfb717df62/test-framework/sudo-compliance-tests/src/sudoers/runas_alias.rs#L321-L352

sudo-rs: passing both `-g` and `-u` arguments at the same time succeeds.

**Comment by squell** [comment]
Asked upstream about this issue, hoping we can become compliant without changing our code. :)

**Comment by millert** [comment]
FYI this has been fixed in sudo by [78e65e1](https://github.com/sudo-project/sudo/commit/78e65e14ea18278a904beddd54b964609b715762)
