### ISSUE TITLE
Inappropriate ioctl for device

### ISSUE THREAD

**Issue by marlonbaeten** [memorysafety/sudo-rs#452]
**Describe the bug**
If I try to run bash with sudo-rs, I get the error:
```
bash: cannot set terminal process group (...some number...): Inappropriate ioctl for device
bash: no job control in this shell
```

**To Reproduce**
1. Build and configure 'sudo-rs'
3. Run `sudo-rs /bin/bash`
4. See the error

**Expected behavior**
No error.

**Environment (please complete the following information):**
 - Linux distribution: Ubuntu 22.04
 - `sudo-rs` commit hash: 16b7df45597d076947b8a6f6e24d66a9392803ea

**Comment by pvdrz** [comment]
Sounds like a `exec` issue.
