### ISSUE TITLE
su does not accept password via stdin

### ISSUE THREAD

**Issue by japaric** [memorysafety/sudo-rs#490]
relevant test

https://github.com/memorysafety/sudo-rs/blob/2f9e09f196c01d993c84d1b81d2bd1ad9c5328e0/test-framework/sudo-compliance-tests/src/su.rs#L71-L83

in a docker container you can repro with:

``` console
$ echo target-user-password | su -c true target-user
```

this works with ogsudo. sudo-rs asks for a password to be entered via the tty

**Comment by marlonbaeten** [comment]
Fixed in https://github.com/memorysafety/sudo-rs/pull/498
