### ISSUE TITLE
Authentication and policy architecture

### ISSUE THREAD

**Issue by rnijveld** [memorysafety/sudo-rs#5]
We'll need to think up of a way to setup the authentication and policy controls before we run the given commands.

Questions:
* Do we want plugins? What is the interface for those plugins?
* How to ensure security here? Can we use the typesystem to enforce application flow?

**Comment by squell** [comment]
Note: most of these early quetions I feel have been answered; i.e.

Not do plugins (right now), but we do want to have a sufficiently abstract interface so we don't expose (beyond the confines of the sudoer crate) unnecessarily to particular details of the sudoers file, which allows creating separate permission crates in the future.
