### ISSUE TITLE
`su` doesn't require the SUDO_RS_IS_UNSTABLE environment variable

### ISSUE THREAD

**Issue by pvdrz** [memorysafety/sudo-rs#510]
**Describe the bug**
I can compile and run `su` without having to set the `SUDO_RS_IS_UNSTABLE` environment variable.

**To Reproduce**
1. Compile `su`: `cargo build --bin su`
3. Run `su` with an empty environment: `env -i ./target/debug/su`
4. No error asking for the `SUDO_RS_IS_UNSTABLE` environment variable is shown

**Expected behavior**
`SUDO_RS_IS_UNSTABLE` should be set to be able to execute `su`

**Environment (please complete the following information):**
 - Linux distribution: Arch Linux with kernel 6.3.8 
 - `sudo-rs` commit hash: 42c1636804c0c75f13a286f2aa20cd1b64ee083f

**Comment by squell** [comment]
I think I'm actually fine with this at this point in development.

**Comment by pvdrz** [comment]
Closed in favor of https://github.com/memorysafety/sudo-rs/issues/525
