### ISSUE TITLE
su-rs spaws more processes than ogsu

### ISSUE THREAD

**Issue by japaric** [memorysafety/sudo-rs#592]
relevant tests

- `--pty` + `Env.tty(true)`

https://github.com/memorysafety/sudo-rs/blob/25d606b0b2add266e1d36b5a3986f1c73f93f6cf/test-framework/sudo-compliance-tests/src/su/flag_pty.rs#L97-L112

- no `--pty` flag + `Env.tty(true)`

https://github.com/memorysafety/sudo-rs/blob/25d606b0b2add266e1d36b5a3986f1c73f93f6cf/test-framework/sudo-compliance-tests/src/su/flag_pty.rs#L68-L81

ogsu
``` console
# su -c 'ps aux'
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.1  0.0   4188  2944 pts/0    Ss   13:49   0:00 bash
root           7  0.0  0.0   4120  2432 pts/0    S+   13:50   0:00 su -c ps aux
root           8  0.0  0.0   8084  4224 pts/0    R+   13:50   0:00 ps aux
```

su-rs
``` console
# su -c 'ps aux'
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.2  0.0   4188  3072 pts/0    Ss   13:50   0:00 bash
root           7 33.3  0.0   6508  3840 pts/0    R+   13:50   0:00 su -c ps aux
root           8  0.0  0.0   6508  1772 pts/1    Ss   13:50   0:00 su -c ps aux
root           9 50.0  0.0   8084  4224 pts/1    R+   13:50   0:00 ps aux
```

**Comment by squell** [comment]
Note: I would guess this problem is not really fixable without creating another `exec_pty` function; and since `--pty` is a `util-linux` extension to `su` we can probably just document that our pty implementation is different (i.e. based on sudo's,which is also probably the more well-tested of the two).

**Comment by japaric** [comment]
closing in favor of #631
