### ISSUE TITLE
su reports unrelated euid in syslog on failed auth

### ISSUE THREAD

**Issue by japaric** [memorysafety/sudo-rs#607]
relevant test:

https://github.com/memorysafety/sudo-rs/blob/be44e6a6f95f6439414d7ffe67806f76c0f13416/test-framework/sudo-compliance-tests/src/su/syslog.rs#L59-L95

``` console
$ whoami
ferris

$ echo | su ghost
```

`/var/log/auth.log`
``` text
2023-06-28T16:22:42.217699+00:00 0507798b77fc su: pam_unix(su:auth): authentication failure; logname= uid=1000 euid=0 tty= ruser=ferris rhost=  user=ghost
```

`euid=0` corresponds to root but root is neither the target or invoking user. also, probably `logname=` should not be empty

**Comment by marlonbaeten** [comment]
`euid` stands for "effective user id" which is 0 for su - since su is a setuid program - so I think the output of `su-rs` is actually correct.
