### ISSUE TITLE
syslog messages could be truncated if too long

### ISSUE THREAD

**Issue by rnijveld** [memorysafety/sudo-rs#626]
Right now our implementation logs no matter the length of the message, but in order to prevent truncating syslog messages we should make sure to not send more than 1024 bytes of message. The best way to do this would be to split up messages if they are too long. ogsudo uses a limit of 960 bytes for the message, because the 1024 bytes includes things like process id and process name.

**Comment by oneElectron** [comment]
Hi there, I am looking to contributes to sudo-rs and I was wondering if I could start with this. I have already made a quick version on my fork: [https://github.com/oneElectron/sudo-rs/tree/626-truncate-syslog](https://github.com/oneElectron/sudo-rs/tree/626-truncate-syslog)

**Comment by squell** [comment]
Nobody else is working on this right now, so go ahead! Submit a PR when you feel your work is ready and someone will review it. Thanks! :)
