### ISSUE TITLE
Visudo should check env variables

### ISSUE THREAD

**Issue by oneElectron** [memorysafety/sudo-rs#723]
ogsudo's visudo reads env variables in order to find the users preferred editor.
This should also be implemented in sudo-rs's visudo.

# Additional context
ogsudo looks at the following environment variables in this order to find an editor:
- SUDO_EDITOR
- VISUAL
- EDITOR

If ogsudo's visudo cannot find the editor in one of those places it falls back to the editor set at build time (default is vi).

I would like to work on this issue myself.

**Comment by oneElectron** [comment]
Upon closer inpection visudo does include this functionality, however setting the EDITOR variable does not work (but VISUAL and SUDO_EDITOR do work).

**Comment by pvdrz** [comment]
That's interesting, there's no special handling for `EDITOR`, it just happens to be the last one we check: https://github.com/memorysafety/sudo-rs/blob/7a2de41cc987888c85d374bebf87d6ac27927ca8/src/sudoers/mod.rs#L119-L133

**Comment by oneElectron** [comment]
Sorry I have made a slight mistake. I thought it wasn't working, but it turns out that I set the EDITOR variable to a command, not the path to the command. I have opened a new issue for this problem: #724
