### ISSUE TITLE
sudoers: null byte terminated username not treated as a syntax error

### ISSUE THREAD

**Issue by japaric** [memorysafety/sudo-rs#749]
relevant test
https://github.com/memorysafety/sudo-rs/blob/cfc735fbb05e5c88541ddfe9e173d452ae1c7340/test-framework/sudo-compliance-tests/src/sudo/sudoers/user_list.rs#L412-L427

ogsudo rejects the sudoers file and does not allow the user to run sudo. sudo-rs lets the user run sudo

**Comment by squell** [comment]
There is an interplay between two issues here:
- a commit that addressed this (and also changes the sentinel value to a more type-safe solution) was never pushed for some reason
- the illegal escape sequence error is suppressed, seems like that happens in the whitespace parser

This is a nice bug, harmless but interesting.
