### ISSUE TITLE
Garbadge output

### ISSUE THREAD

**Issue by vit1251** [memorysafety/sudo-rs#783]
```
/etc/sudoers:78:9: expected parameter
Defaults:WHEEL_USERS !env_reset
        ^
/etc/sudoers:82:9: expected parameter
Defaults:XGRP_USERS env_keep += "DISPLAY XAUTHORITY"
        ^
```
How to enable support `Defaults`?

**Comment by squell** [comment]
Thanks for requesting this feature.

As mentioned in the README: 
> Per-user, per-command, per-host Defaults sudoers entries for finer-grained control are not (yet) supported.

I.e., currently there is no work-around, but this is something on the "to do" list when work starts on Milestone 4.

The implementation of this is tracked by issue #61.
