### ISSUE TITLE
sudoers: `%root` and `%#0` fail with 'Error: Authentication("no permission")'

### ISSUE THREAD

**Issue by japaric** [memorysafety/sudo-rs#99]
failing tests:

https://github.com/memorysafety/sudo-rs/blob/e5233df26ea0d5f46f71707bb78c54631065305d/test-framework/sudo-compliance-tests/src/sudoers/user_list.rs#L66

https://github.com/memorysafety/sudo-rs/blob/e5233df26ea0d5f46f71707bb78c54631065305d/test-framework/sudo-compliance-tests/src/sudoers/user_list.rs#L79

the original sudo passes both tests

**Comment by squell** [comment]
This is probably a duplicate of #82; merging #86 should fix it.

**Comment by japaric** [comment]
#86 indeed fixes those two tests. as the tests are added in #98 I'll put the "closing" comment in that PR
